name: scrapers-comprasnet
services:
  postgresql:
    image: postgres:17.4
    container_name: scrapers-postgres
    restart: unless-stopped
    volumes:
       - licitacao-postgresql-data:/var/lib/postgresql/data/
       - ./docker/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=scraper
      - POSTGRES_PASSWORD=scraper
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5432:5432
  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: scrapers-rabbitmq
    restart: unless-stopped
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - licitacao-rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
        test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: scrapers-minio-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: B@sis123
    command: server /data --console-address ":9001"
    volumes:
      - licitacao-minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  mattermost:
    depends_on:
      - postgresql
    image: mattermost/mattermost-team-edition:10.6.1@sha256:787b839dc79647b097ea292362f4a905291cafab1c8ddc8d784d23da537aa084
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    ports:
      - 8065:8065
      - 8443:8443/udp
      - 8443:8443/tcp
    tmpfs:
      - /tmp
    volumes:
      - mattermostconfig:/mattermost/config:rw
      - mattermostdata:/mattermost/data:rw
      - mattermostlogs:/mattermost/logs:rw
      - mattermostplugins:/mattermost/plugins:rw
      - mattermostclientplugins:/mattermost/client/plugins:rw
      - mattermostbleve-indexes:/mattermost/bleve-indexes:rw
    environment:
      - TZ=America_SaoPaulo
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mattermost:mattermost@postgresql:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - MM_SERVICESETTINGS_SITEURL=http://mattermost.local
  redis:
    image: redis:7.2.5
    restart: unless-stopped
    container_name: licitacao-redis
    volumes:
      - licitacao-redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6379:6379
volumes:
  licitacao-postgresql-data:
    driver: local
  licitacao-rabbitmq-data:
    driver: local
  licitacao-minio-data:
    driver: local
  mattermostconfig:
    driver: local
  mattermostdata:
    driver: local
  mattermostlogs:
    driver: local
  mattermostplugins:
    driver: local
  mattermostclientplugins:
    driver: local
  mattermostbleve-indexes:
    driver: local
  licitacao-redis-data:
    driver: local
