vars: {
  d2-config: {
    layout-engine: dagre
    theme-id: 100
    sketch: true
    center: true
  }
}

explanation: |md
  # RabbitMQ Exchanges e Filas
| {near: top-center}

direction: right

Usuario{
  icon: https://icons.terrastruct.com/dev%2Fjava.svg
  style{
    font-size : 40
  }
}

Consumidor-admin{
  icon: https://icons.terrastruct.com/dev%2Fjava.svg
  style{
    font-size : 40
  }
}

Consumidor-chat-mattermost{
  icon: https://icons.terrastruct.com/dev%2Fjava.svg
  style{
    font-size : 40
  }
}

rabbit1: RabbitMQ {
  icon: https://www.svgrepo.com/show/303576/rabbitmq-logo.svg
  Exchange-pregao-info: {
    shape: queue
    style.fill: chocolate
    style.font-size : 40
  }
  pregao-dados-propostas: {
    shape: queue
    style.fill: orange
    style.font-size : 40
}
}
proposta-dados-gerais{
  icon: https://icons.terrastruct.com/dev%2Fpython.svg
  style{
    font-size : 40
  }
}

rabbit2: RabbitMQ {
  icon: https://www.svgrepo.com/show/303576/rabbitmq-logo.svg
  dados-propostas {
    shape: queue
    style.fill: chocolate
    style.font-size : 40
  }
  fila1:dados-propostas.admin {
    shape: queue
    style.fill: orange
    style.font-size : 40
}
  fila2:dados-propostas.chat-mattermost {
    shape: queue
    style.fill: orange
    style.font-size : 40
}
}
Usuario -> rabbit1.Exchange-pregao-info: {
  style.animated: true
  style.stroke: red
}

rabbit1.Exchange-pregao-info -> rabbit1.pregao-dados-propostas

rabbit1.pregao-dados-propostas -> proposta-dados-gerais: {
  style.animated: true
  style.stroke: blue
}

proposta-dados-gerais -> rabbit2.dados-propostas: {
  style.animated: true
  style.stroke: red
}
rabbit2.dados-propostas -> rabbit2.fila1
rabbit2.dados-propostas -> rabbit2.fila2


rabbit2.fila1 -> Consumidor-admin : {
  style.animated: true
  style.stroke: blue
}
rabbit2.fila2 -> Consumidor-chat-mattermost : {
  style.animated: true
  style.stroke: blue
}